TOP = ..

include $(TOP)/mk/prelude.mk

NAME = ccc
all: $(NAME)$(EXEC)

OBJS = main.o

include ../misc/InfoMakefile
include ../lang/*/InfoMakefile
include ../cg/*/InfoMakefile
include ../ie/*/InfoMakefile
include ../ow/*/InfoMakefile

include $(TOP)/mk/rules.mk
