#include "pargen.h"

static int version(const char* argv0, const char* flag, const char* option) {
	printf("%s\n", COPYRIGHT(PARGEN_PART, PARGEN_VERSION));

	return 0;
}

static int help(const char* argv0, const char* flag, const char* option) {
	char pad[32];

	version(argv0, flag, option);

	printf("Usage: %s input\n", argv0);
	printf("       %s -v (shows version)\n", argv0);
	printf("       %s -h (shows this help)\n", argv0);

	return 0;
}

static cmd_command_t commands[] = {
    {"v", 0, version},
    {"h", 0, help},
    {NULL, 0, NULL}};

static FILE* in = NULL;
static int   insz;
static char* inbuf;

static int input(const char* argv0, const char* flag, const char* option) {
	if(in != NULL) {
		fprintf(stderr, "%s: only takes one input\n", argv0);

		return 1;
	}

	if((in = fopen(option, "r")) == NULL) {
		fprintf(stderr, "%s: cannot open file `%s'\n", argv0, option);
		return 1;
	}

	return -1;
}

static void parse(void) {
	char* lbuf;
	char* line;
	char* gbuf;
	int   i;

	line = lbuf = inbuf;
	for(i = 0; i <= insz; i++) {
		int c;

		if(i == insz) {
			c = EOF;
		} else {
			c = *lbuf++;
		}

		if(c == '\n' || c == EOF) {
			int lsz = lbuf - line - (c == '\n' ? 1 : 0);

			if(lsz == 2 && memcmp(line, "%%", 2) == 0) {
				gbuf = lbuf;

				break;
			} else {
				fwrite(line, 1, lbuf - line, stdout);
			}

			line = lbuf;
		}
	}

	if(i != insz) {
		char* sbuf = gbuf; /* saved buffer */
		int   c	   = 0;
		char  rules[128][128];
		int   where;

		memset(rules, 0, sizeof(rules));

#define LenCheck(in) (((in) - inbuf) < insz)
#define IsSkippable(x) ((x) == ' ' || (x) == '\t' || (x) == '\n')
#define SkipSkippable(todo) \
	{ \
		while(LenCheck(gbuf) && IsSkippable(*gbuf)) gbuf++; \
		if(!LenCheck(gbuf)) { \
			todo; \
			return; \
		} \
	}

	reread:;
		c++;
		if(c == 3) {
			return;
		}

		gbuf  = sbuf;
		where = 0;

		while(LenCheck(gbuf) && IsSkippable(*gbuf)) gbuf++;
		if(!LenCheck(gbuf)) return;

		while(LenCheck(gbuf)) {
			/* label */
			while(LenCheck(gbuf) && !IsSkippable(*gbuf) && *gbuf != ':') {
				if(c == 1) rules[where][strlen(rules[where])] = *gbuf;
				gbuf++;
			}
			if(!LenCheck(gbuf)) return;

			SkipSkippable({});

			/* colon */
			if(*gbuf++ != ':') return;
			if(!LenCheck(gbuf)) return;

			if(c == 2) {
				printf("static void rule_%s(ILexer* lexer){\n", rules[where]);
			}

		another_rule:;
			SkipSkippable({});

		another_node:;
			while(LenCheck(gbuf) && !IsSkippable(*gbuf) && *gbuf != '|' && *gbuf != ';') {
				gbuf++;
			}

			SkipSkippable({});

			/* semicolon */
			if(*gbuf == '|') {
				gbuf++;

				goto another_rule;
			} else if(*gbuf == ';') {
				gbuf++;

				SkipSkippable({
					if(c == 1) {
						printf("\n");
					}
					goto reread;
				});

				if(c == 1) {
					printf("static void rule_%s(ILexer* lexer);\n", rules[where]);
				} else {
					printf("}\n");
					printf("\n");
				}

				where++;
				continue;
			}

			goto another_node;
		}
	}
}

int main(int argc, char** argv) {
	int st;

	if(argc == 1) {
		help(argv[0], "h", NULL);
		return 0;
	}

	if((st = cmd_option(argc, argv, commands, input)) != -1) return st;

	fseek(in, 0, SEEK_END);
	insz = ftell(in);
	fseek(in, 0, SEEK_SET);

	inbuf = malloc(insz);
	fread(inbuf, 1, insz, in);

	fclose(in);

	printf("/**\n");
	printf(" * Generated by: %s\n", COPYRIGHT(PARGEN_PART, PARGEN_VERSION));
	printf(" * It is NOT recommended to edit this file manually\n");
	printf(" */\n");

	parse();

	free(inbuf);
}
